console.log('In this program all number function are hare');
let x = parseInt(process.argv[2]);
let y = parseInt(process.argv[3]);
console.log('the sum is:');
console.log(x+y);
console.log('the sub is:');
console.log(x-y);
console.log('the mul is:');
console.log(x*y);
console.log('the div is:');
console.log(x/y);

let a= parseFloat(10.50);
let b = parseFloat(5.20);
console.log('the sum is:');
console.log(a+b);
console.log('the sub is:');
console.log(a-b);
console.log('the mul is:');
console.log(a*b);
console.log('the div is:');
console.log(a/b);